version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  db:
    image: "postgres:9.6.5"
    # volumes:
    #   - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    ports:
      - "5432:5432"


  flaskapp:
    build: app
    expose:
      - "5000"
    ports:
      - "5050:5000"
    volumes:
      - ./app:/app/
    depends_on:
      - db

  web:
    container_name: nginx
    build: www
    ports:
      - "9090:80"
    command: nginx -g "daemon off";
    depends_on:
      - flaskapp
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
