version: "3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  db:
    restart: always
    container_name: postgres_db
    image: "postgres:9.6.17"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    env_file:
      - env_file
    expose:
      - "5432"

  web:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    ports:
      - "8181:80"
    command: nginx -g "daemon off";
    depends_on:
      - python_api
      
  python_api:
    container_name: python_api
    build:
      context: .
      dockerfile: Dockerfile_Flask
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 1 -b :8000 app:app
    # command: tail -f /dev/null
    restart: always
    depends_on:
      - db

volumes:
  postgres_data: