FROM python:3.7.7

WORKDIR /usr/src/app

COPY app /usr/src/app/app
COPY requirements.txt /usr/src/app
COPY config /usr/src/app/config

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

