version: "3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  db:
    restart: always
    container_name: postgres_db
    image: "postgres:9.6.17"
    volumes:
      - "test_talla:/var/lib/postgresql/data"
    env_file:
      - env_file
    ports:
      - 5432:5432

  python_api:
    container_name: python_api
    build:
      context: .
      dockerfile: Dockerfile_Flask
    environment:
      - APP_CONFIG=production
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn -w 1 -b :8000 app:create_app()
    # command: tail -f /dev/null
    restart: always
    depends_on:
      - db

volumes:
  postgres_test_data:
  postgres_prod_data:
  postgres_test:
  test_tsest:
  test_tsest2:
  test_talla:
