import os
import regexgen

HOST_LIST = [
    "nl2p-gigc-lea01.fabric.gigcloud.io",
    "nl2p-gigc-lea02.fabric.gigcloud.io",
    "nl2p-gigc-lia01.fabric.gigcloud.io",
    "nl2p-gigc-lia02.fabric.gigcloud.io",
    "nl2p-gigc-leb01.fabric.gigcloud.io",
    "nl2p-gigc-leb02.fabric.gigcloud.io",
    "nl2p-gigc-lib01.fabric.gigcloud.io",
    "nl2p-gigc-lib02.fabric.gigcloud.io",
    "nl2p-gigc-fsa01.fabric.gigcloud.io",
    "nl2p-gigc-fsa02.fabric.gigcloud.io",
    "nl2p-gigc-mqa01.fabric.gigcloud.io",
    "nl2p-gigc-mqa02.fabric.gigcloud.io",
    "nl2p-gigc-mqa03.fabric.gigcloud.io",
    "nl2p-gigc-mqb01.fabric.gigcloud.io",
    "nl2p-gigc-mqb02.fabric.gigcloud.io",
    "nl2p-gigc-mqb03.fabric.gigcloud.io",
    "nl2p-gigc-mqc01.fabric.gigcloud.io",
    "nl2p-gigc-mqc02.fabric.gigcloud.io",
    "nl2p-gigc-mqc03.fabric.gigcloud.io",
    "nl2p-spnc-mqa01.fabric.gigcloud.io",
    "nl2p-spnc-mqa02.fabric.gigcloud.io",
    "nl2p-spnc-mqa03.fabric.gigcloud.io",
    "nl2p-rzkc-mqa01.fabric.gigcloud.io",
    "nl2p-rzkc-mqa02.fabric.gigcloud.io",
    "nl2p-rzkc-mqa03.fabric.gigcloud.io",
    "nl2p-gigc-rda01.fabric.gigcloud.io",
    "nl2p-gigc-rda02.fabric.gigcloud.io",
    "nl2p-gigc-rda03.fabric.gigcloud.io",
    "nl2p-gigc-rda04.fabric.gigcloud.io",
    "nl2p-gigc-rda05.fabric.gigcloud.io",
    "nl2p-gigc-esa01.fabric.gigcloud.io",
    "nl2p-gigc-esa02.fabric.gigcloud.io",
    "nl2p-gigc-esa03.fabric.gigcloud.io",
    "nl2p-gigc-lga01.fabric.gigcloud.io",
    "nl2p-gigc-lga02.fabric.gigcloud.io",
    "nl2p-gigc-lga03.fabric.gigcloud.io",
    "nl2p-gigc-lgb01.ds.gigcloud.io",
    "nl2p-gigc-lgb02.ds.gigcloud.io",
    "nl2p-gigc-esc01.ds.gigcloud.io",
    "nl2p-gigc-esc02.ds.gigcloud.io",
    "nl2p-gigc-esc03.ds.gigcloud.io",
    "nl2p-gigc-pga01.ds.gigcloud.io",
    "nl2p-gigc-pga02.ds.gigcloud.io",
    "nl2p-gigc-pba01.ds.gigcloud.io",
    "nl2p-gigc-mca01.ds.gigcloud.io",
    "nl2p-gigc-mca02.ds.gigcloud.io",
    "nl2p-gigc-mca03.ds.gigcloud.io",
    "nl2p-gigc-mca04.ds.gigcloud.io",
    "nl2p-gigc-mwa01.ds.gigcloud.io",
    "nl2p-gigc-mwa02.ds.gigcloud.io",
    "nl2p-ghfc-apa01.ds.gigcloud.io",
    "nl2p-ghfc-apa02.ds.gigcloud.io",
    "nl2p-gutc-apa01.ds.gigcloud.io",
    "nl2p-gutc-apa02.ds.gigcloud.io",
    "nl2p-guxc-apa01.ds.gigcloud.io",
    "nl2p-guxc-apa02.ds.gigcloud.io",
    "nl2p-lkdc-apa01.ds.gigcloud.io",
    "nl2p-lkdc-apa02.ds.gigcloud.io",
    "nl2p-mglc-apa01.ds.gigcloud.io",
    "nl2p-mglc-apa02.ds.gigcloud.io",
    "nl2p-1n1c-apa01.ds.gigcloud.io",
    "nl2p-1n1c-apa02.ds.gigcloud.io",
    "nl2p-otpc-apa01.ds.gigcloud.io",
    "nl2p-otpc-apa02.ds.gigcloud.io",
    "nl2p-skcc-apa01.ds.gigcloud.io",
    "nl2p-skcc-apa02.ds.gigcloud.io",
    "nl2p-thrc-apa01.ds.gigcloud.io",
    "nl2p-thrc-apa02.ds.gigcloud.io",
    "nl2p-bspc-apa01.ds.gigcloud.io",
    "nl2p-splc-apa01.ds.gigcloud.io",
    "nl2p-bytc-apa01.ds.gigcloud.io",
    "nl2p-bytc-apa02.ds.gigcloud.io",
    "nl2p-mrgc-apa01ds.gigcloud.io",
    "nl2p-mrgc-apa02ds.gigcloud.io",
    "hr1p-rzkc-apa01ds.gigcloud.io",
    "hr1p-rzkc-apa02ds.gigcloud.io",
    "nl2p-gutc-fea01ds.gigcloud.io",
    "nl2p-gutc-fea02ds.gigcloud.io",
    "nl2p-gutc-fea03ds.gigcloud.io",
    "nl2p-gutc-fea04ds.gigcloud.io",
    "nl2p-1n1c-fea01ds.gigcloud.io",
    "nl2p-1n1c-fea02ds.gigcloud.io",
]

if __name__ == "__main__":
    t = regexgen.List(HOST_LIST)
    print(t)


