
POST http://127.0.0.1:8181/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "username": "renemifsud",
    "password": "renetest",
    "email": "renemifsud@gmail.com"
}

###
GET http://127.0.0.1:8181/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Basic eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTg4MDgwMzM4fQ.bOFCQBAPR8qi62ez-I1iIT9PgRk61T7ZjmCf78B90yg:

###
GET http://127.0.0.1:5000/get-auth-token HTTP/1.1
Content-Type: application/json
Authorization: Basic renemifsud:renetest