POST http://127.0.0.1:5000/alerts HTTP/1.1
Content-Type: application/json
Authorization: Basic eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTkzMzMwNTU3fQ.hrwhN2AFTFhTIBIRhDct-ATJEgWoKwqvT6pJOXY6_IM:

{
    "username": "renemifsud",
    "password": "renetest",
    "email": "renemifsud@gmail.com"
}

###
GET http://127.0.0.1:5000/alerts HTTP/1.1
Content-Type: application/json
Authorization: Basic eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTkzMzMwNTU3fQ.hrwhN2AFTFhTIBIRhDct-ATJEgWoKwqvT6pJOXY6_IM:
